name: Hestia.Serilog.Sinks.AliCloud.SLS

on:
  workflow_dispatch:

jobs:
  Publish:
    env:
      PROJECT: Hestia.Serilog.Sinks.AliCloud.SLS
      NUGET: https://api.nuget.org/v3/index.json
    environment: release
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore
      run: dotnet restore --verbosity minimal ./${{ env.PROJECT }}/src/${{ env.PROJECT }}.csproj
    - name: Build
      run: dotnet build --no-restore --verbosity minimal --configuration Release ./${{ env.PROJECT }}/src/${{ env.PROJECT }}.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release ./${{ env.PROJECT }}/src/${{ env.PROJECT }}.csproj
    - name: Pack
      run: dotnet pack --no-build --verbosity normal --configuration Release ./${{ env.PROJECT }}/src/${{ env.PROJECT }}.csproj
    - name: NuGet OIDC
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}    
    - name: Push
      run: dotnet nuget push ./${{ env.PROJECT }}/src/bin/Release/*.nupkg --skip-duplicate --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source {{ env.NUGET }}
      
